# First stage image labelled as node-angular-cli
FROM nginx:latest
LABEL authors="Altran"

RUN apt update -y \
    && apt upgrade -y \
    && apt install -y nodejs \
    && npm install \
    && ng build --prod
    
# Copying dist folder 
COPY dist/AIlabCDP/ /var/www/

COPY default.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
