# First stage image labelled as node-angular-cli
FROM nginx:latest
LABEL authors="Altran"

# Copying dist folder 
COPY dist/AIlabCDP/ /var/www/

RUN apt-get update -y
RUN apt-get upgrade -y

COPY default.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
